### PR TITLE
Fix [datetimepicker] iOS 14 compatibility

### LINKED ISSUE #11: [datetimepicker] iOS 14 compatibility?
I am trying to make it work on iOS 14 (NS 7+Angular 10) and this is how it looks like:
Greenshot 2020-09-18 09 44 24

### PR DESCRIPTION
**Pull request by alexander-mai**
Fix https://github.com/NativeScript/plugins/issues/11

* changes from https://github.com/NativeScript/NativeScript/pull/8876

### CODE REVIEW

**Comment by 3rror404** [comment]
Any news on this PR? It seems to be working great for me. Thanks @alexander-mai

**Comment by NathanWalker** [comment]
@alexander-mai thank you for this - published in `2.0.3`

**Comment by alexander-mai** [comment]
Could you please also merge this fix for the old version 1.x @NathanWalker?
https://github.com/NativeScript/nativescript-datetimepicker/pull/76

**Comment by richardman1** [comment]
@NathanWalker can that fix be applied to the 1.x version as mentioned above?

**Comment by NathanWalker** [comment]
Will do - likely by tonight or earlier.

**Comment by NathanWalker** [comment]
@richardman1 published in nativescript-datetimepicker@1.2.3 now.

**Pull request merged**
