### PR TITLE
fix(directions): Add option to use Universal URL Scheme for Google Maps

### LINKED ISSUE #135: [@nativescript/directions] Google Maps opens and does not load the route
# Overview 
When opening Google Maps using the plugin, if google maps is not already open it will hang showing the expected destination.

This appears to be intermittent, if you switch back to your app and tap your button again Google Maps loads the route.

Have noticed the issue on iOS and need to retest on android.

# Suggested Fix
Updating the URL in the plugin to use the [Universal URL](https://developers.google.com/maps/documentation/urls/get-started#directions-action) opens maps with the route loaded first time as expected.

This is iOS 9.0+, so should not impede compatibility.

Will knock up a fix and get a PR up tomorrow.

### PR DESCRIPTION
**Pull request by jamescodesthings**
Fixes #135 ish.

- Found that google maps does not load correctly first time when using lat & lng.
- When hacking around the module found using the updated Universal URL syntax works.
- Added an option to use the Universal URL Scheme when google maps is chosen.

Squash Of:

commit b258cb907eda0fcd3c815572b962290ab123d4ca
Author: JamesCodesThings <james.macmillan@engineius.co.uk>
Date:   Wed Jun 2 15:56:58 2021 +0100

    make sure it works in the same way on android

commit 95797840d35d8e52e6bbc9e96b49a8b41d42599a
Author: JamesCodesThings <james.macmillan@engineius.co.uk>
Date:   Wed Jun 2 15:16:00 2021 +0100

    Fix up Universal URL Scheme

commit 48a1c5d05f53c5601af7c4f2ed0aff67311cc4c2
Author: JamesCodesThings <james.macmillan@engineius.co.uk>
Date:   Wed Jun 2 11:26:10 2021 +0100

    update demo-angular to something useful

commit fd9fd94dbfc77b02d86f0609defd9e89785b1577
Author: JamesCodesThings <james.macmillan@engineius.co.uk>
Date:   Wed Jun 2 09:40:36 2021 +0100

    stash

commit 14966eade382f94fb8dac7611fb95b40936b2a63
Author: JamesCodesThings <james.macmillan@engineius.co.uk>
Date:   Tue Jun 1 10:50:13 2021 +0100

    chore(directions): clean up index.ios.ts

    - Reduce nesting in the navigate method
    - Introduce optional chaining to reduce the if condition length/complexity.

### CODE REVIEW

**Comment by jamescodesthings** [comment]
@cla-bot check

**Comment by jamescodesthings** [comment]
Temporary fork available under `@codesthings/directions` for testing purposes.

`npm install --save --save-exact @codesthings/directions @nativescript/directions@npm:@codesthings/directions` to proxy in.

**Comment by asharghi** [comment]
Has this been merged to original repo?

**Comment by jamescodesthings** [comment]
@asharghi Nope, this is the PR to ask for it to be merged in.

**Comment by asharghi** [comment]
Nice, thanks for fixing this 🙌🏼 hope this gets merged soon

**Comment by NathanWalker** [comment]
Very nice @jamescodesthings 🤗 thank you.

**Comment by NathanWalker** [comment]
Published with 2.0.1 now.

**Comment by asharghi** [comment]
Tested this today. The new version doesn't longer open Google Maps on iOS. On the previous version of the plugin it would automatically use Google Maps if it was installed. Now you are sent to the AppStore to download Apple Maps.

**Comment by jamescodesthings** [comment]
Hey @asharghi, sorry about this, there's an odd set of boolean settings to make sure are correct to get this open correctly.

For opening in google maps by default you want something like this:
```ts
// Navigates to google maps with Universal syntax as the preference.
return this.directions.navigate({
      to,
      ios: {
        preferGoogleMaps: true,
        allowGoogleMapsWeb: true, // Don't remember if this one is absolutely necessary when using useUniversalSyntax
      },
      type: 'driving',
      useUniversalSyntax: true,
});
```

I've just noticed an error in the readme demo where `useUniversalSyntax` is under the `.ios` key, this moved to the base Options object because it applies to both android and iOS. 

If you set all the three above keys to true then Google Maps via Universal URL is preferred.

**Comment by asharghi** [comment]
Hi @jamescodesthings. Tested this some more now. If preferGoogleMaps is set to true then it will open Google Maps. But having it set to true with the device not have Google Maps installed should open Apple Maps (right now it's sent to the web version, even when allowGoogleMapsWeb is set to false). On the previous version this worked fine, the solution was: if Google Maps is installed use that, if not use Apple Maps.

**Comment by jamescodesthings** [comment]
Hey @asharghi Unfortunately that's a side-effect of using the universal scheme. 

The universal url scheme basically just says "i'm not fussed if you open google maps or google maps on the web, just handle it". I don't think there's any immediate way to check via the universal scheme if Google Maps is going to be used.

In my app I have a separate setting to allow the user to set their preference.

**Pull request merged**
