### PR TITLE
Don't use NSInvoke to get task attributes.

### PR DESCRIPTION
**Pull request by boutier**
I've experimented, on iOS 14.0.1, that `invocation.getReturnValue(ret)` raises:
```
[NSInvocation getArgument:atIndex:]: NULL address argument
```

However, using invocations seems no more needed since the properties we're
fetching are directly available from the task object.

### CODE REVIEW

**Comment by boutier** [comment]
> 3. Make sure that the git commit email is configured in your GitHub account settings, see https://github.com/settings/emails

Done.

**Comment by NathanaelA** [comment]
1. Do you know if this change would still work on iOS 9/10?   Or do we need to detect OS version to see if it works.
2. Any chance you can fix the PR; it appears that your editor reformatted the code and so it is impossible to see exactly what changed.

**Comment by boutier** [comment]
1. Actually I don't know. I thought that accessing these fields was related to the nativescript version.

2. It's not my editor but some git commit hook. Only changed files are reformated and I thought it was intentional. Maybe some configuration file is missing in the repository (and not defined globally)?

(I'm not with my computer this week-end and so will not be able to recommit before Monday.)

**Comment by boutier** [comment]
1. Still didn't check, but the apple documentation describes NSURLSessionTask as available since iOS 7, and note that `_task.description` was already accessed without invocations. (https://developer.apple.com/documentation/foundation/nsurlsessiontask)

(That said, I didn't see any good reasons why these invocations are not working anymore and I'd be happy if anyone teach me.)

2. Looking at the `.prettierrc`, there actually is `"useTabs": true`and `"singleQuote": true`. Please either update these rules or do a refactoring commit since the pre-commit hook will reformat. For this time, I've removed the hook to fulfill your will since I don't know what is faulty: the `prettierrc` or the file format.

3. Something bother me about signing the CLA: my postal address is likely to change and I will certainly never even thinking to change it. In addition, I don't understand the purposes of signing the CLA since it's a pull request on an Apache 2 licence project: if I change the licence, you will see it in the pull request, right? So, in fact, it's useless, or I missed something while reading what I should sign, which is worse (in this case having a "what differ from apache 2" paragraph would be nice). Please enlighten me.

**Comment by benediktveith** [comment]
Any updates?

**Comment by Exigency** [comment]
Curious to know if there is an official fix planned, would prefer to avoid going down the manual patch route.

**Comment by boutier** [comment]
@benediktveith, @Exigency, we're quite stuck here:
* because the nativescript team has no lawyers, they prefer to keep a CLA that (if I well understood) has been established by the Progress team (that had lawyers),
* because (i) I'm not a lawyer, (ii) my company don't have lawyers and (iii) I don't feel comfortable about signing something I don't really understand and for which I don't know what are the implications (e.g. shall I keep up-to-date my personal (i.e. address) informations for the rest of my life?), (iv) I deem useless to have a CLA in this case since it's not a patch in an email but a pull request coming from a repository that has an apache2 LICENCE file; then I didn't have yet signed the CLA, and… regarding of what I've written, it's quite unlikely I would did it.

So to move forwards, here are the options I see:
1. close the pull request, report the issue and let the nativescript team redo some patch,
2. leverage the CLA such that pull requests from an Apache2 repository are accepted,
3. just ask to have something like "LICENCE: Apache License 2.0" in each commit message,
4. ask to have a full copy of the Apache 2 licence in each commit message (eh!),
5. if someone doesn't care about all of this bureaucracy, he may just clone my repo, sign the CLA and do the pull request (I guess it would be accepted?!).

**Comment by NathanWalker** [comment]
@boutier thank you for this pull request. We're confirming a few things on older devices to know for sure and will get this merged and published by end of this week.

**Review by NathanWalker — APPROVED** [review]

**Comment by NathanWalker** [comment]
Published in `5.0.1` - thanks again @boutier !

**Comment by boutier** [comment]
Thanks @NathanWalker, @NathanaelA and all the Nativescript Team for your great job! Hoping to contribute more! :-)

**Pull request merged**
