### PR TITLE
docs: correct typo in readme

### PR DESCRIPTION
**Pull request by zeejay09**
Corrected the typo of a word at line 13 of README.md from 'bellow' to 'below'.

### CODE REVIEW

**Review by wSedlacek — APPROVED** [review]

**Comment by zeejay09** [comment]
@cla-bot check

**Review by wSedlacek — CHANGES_REQUESTED** [review]
@zeejay09 Can you update your commit message to follow the conventional commit standards?

**Comment by zeejay09** [comment]
> @zeejay09 Can you update your commit message to follow the conventional commit standards?

Okay sure, no problem.

**Comment by wSedlacek** [comment]
We will want to use the `docs` scope for this.

**Comment by zeejay09** [comment]
Okay thanks for the correction.

**Review by wSedlacek — APPROVED** [review]
Thank you for eye for detail!

**Pull request merged**
