### PR TITLE
[@nativescript/local-notifications] Add full support for Android 12 (API 31)

### PR DESCRIPTION
**Pull request by agonper**
This PR includes the following changes:
- It bumps the compile and target SDK to API 31 in the native-src project.
- It adds all the missing mutability flags for all the PendingIntents declared by the plugin.
- It replaces the intermediate service start on notification tap and calls directly the activity with the MAIN action. Due to this, plugin lifecycle callbacks have to be configured at application startup to initialize the notification handlers, i.e., the plugin now has to be imported in the main application file, both for iOS and Android.
- It includes some fixes to native string equality checks.
- It updates the demo main file to reflect the need to import the plugin during application startup.
- It updates the docs to reflect the new changes in plugin setup and usage
- It bumps plugin version to 6.0.0 due to the breaking changes in the way the plugin behaves.

**Breaking changes:**
- Now the plugin has to be imported at application startup no matter what the platform.
- `launch` config option for notification actions will only work while targeting SDK 30 or lower (starting from Android 12, there's [no way to start an activity now from a service](https://developer.android.com/about/versions/12/behavior-changes-12#notification-trampolines)). It should be deprecated and removed in future releases.

-------------------------
Plugin build does not seem to copy the `.aar` file inside `plugins/android`. It has to be manually copied to the dist folder in order to pack / build the plugin. I couldn't find the reason behind this behavior. It seems that something is excluding `.aar` files from being included in the `dist` folder.

### CODE REVIEW

**Comment by NathanWalker** [comment]
Just excellent @agonper thank you! I’ll fix the .aar handling when I merge this in next couple days.

**Review by NathanWalker — APPROVED** [review]

**Comment by NathanWalker** [comment]
published with @nativescript/local-notifications@6.0.0

**Comment by agonper** [comment]
> Just excellent @agonper thank you! I’ll fix the .aar handling when I merge this in next couple days.

You're welcome @NathanWalker! Thank you for handling the .aar issue, and for the quick merge 🙂

**Comment by chrum** [comment]
hey,

Any chance to integrate that change in NS < 7 version of the plugin?

best!

**Comment by agonper** [comment]
Hello @chrum,

I don't know the policy of the maintainers regarding patching older versions. Maybe you could fork an old version, cherry-pick the changes and fix any inconsistencies. You can pack the resulting version and install it locally to your app repo.

Another option, if your plan to transition to NS8 at some moment, is to pin your targetSdk to 30 (in your app.gradle file), which is still allowed for Play Store uploads: https://developer.android.com/google/play/requirements/target-sdk.

Hope this helps.

**Comment by chrum** [comment]
hey, 

Sure thing that i might be getting to that but it was easier to ask first fot the plans ;)

best!

**Pull request merged**
