### PR TITLE
Feature/android background permission

### PR DESCRIPTION
**Pull request by siewedu**
ACCESS_BACKGROUND_LOCATION has been introduced with Android SDK API level 29 which is required in order to access the location while the app is in background. (https://developer.android.com/training/location/permissions). Currently there is no way to request for background location with this plugin. I added the `always` option which already exists on the iOS API also to the Android API, which can be used to request the background location. I also added the already existing `openSettingsIfLocationHasBeenDenied` option to the Android API so the user will be taken to the settings in case the user has previously denied location permission. 

Unfortunately the openSettingsIfLocationHasBeenDenied option was kind of broken with the introduction of the 'one time' permission in Android 11 (API Level 30). It is practically impossible to differentiate between the case where user has given a 'one time' permission and the case where the 'don't ask again' option was selected. For a detailed explanation see [here](https://github.com/dpa99c/cordova-diagnostic-plugin/issues/422) or [here](https://github.com/Baseflow/flutter-geolocator/issues/662).

This forces us to handle both cases in the same way. I chose to try to request the permission in both cases which ensures that the system permission prompt is always presented again to the user if he gave a 'one time' permission. On the other hand it means that the user won't be taken to the settings on Android 11 after he denied the permission twice during the installation lifetime of the app, even if the `openSettingsIfLocationHasBeenDenied` option is true. 
https://developer.android.com/training/permissions/requesting#one-time
But this seems to be the preferred way according to the Android guidelines which state specifically "to not link to system
settings in an effort to convince the user to change their decision".

### CODE REVIEW

**Comment by NathanWalker** [comment]
This is awesome @siewedu thank you. Lemme see if @triniwiz can help review this.

**Review by triniwiz — APPROVED** [review]
LGTM

**Comment by NathanWalker** [comment]
@siewedu this is published with 7.2.0 - we bumped the minor just in case it affected any projects using `~` at moment.
Thanks again!

**Comment by siewedu** [comment]
Thanks!

**Pull request merged**
