### PR TITLE
feat(geolocation) : Using coarse location on Android 12

### LINKED ISSUE #196: [@nativescript/geolocation] android 12: No location is returned if the new approximate location option is selected
Hi, we recently updated a test device to Android 12 and came across an issue with the geolocation plugin.

We are calling the enableLocationRequest function and the new Android 12 permission request comes up and we then choose approximate location on the device. Calling getCurrentLocation afterwards throws an error with just the following content
`{ "android.permission.ACCESS_FINE_LOCATION": false }`.

First we tried changing the accuracy when fetching the location, but using CoreTypes.Accuracy.high or CoreTypes.Accuracy.any makes no difference.
We also tried to request both ACCESS_FINE_LOCATION and ACCESS_COARSE_LOCATION together. We got nearly the same error `{
  "android.permission.ACCESS_FINE_LOCATION": false,
  "android.permission.ACCESS_COARSE_LOCATION": true
}` but no location even though ACCESS_COARSE_LOCATION was granted.

If fine location access in granted on the device, getCurrentLocation returns the correct location.

What do we need to do in order to allow the user to use only approximate location on Android 12?
Thank you in advance 😊

### PR DESCRIPTION
**Pull request by INiiS**
Should fix #196 

This is my first PR on the project, I hope it follows correctly any guideline, or recommendation.

In Android 12, the user can now choose between fine location & coarse location.
The official android guidelines recomment to request both in the same request, and then handle the result as seen fit.
I tried to follow these guidelines in my implementation.

I closed the previous PR, due to problems on my side with settings correctly my identity on Git. Should be resolved now.

### CODE REVIEW

**Comment by INiiS** [comment]
@cla-bot check

**Review by NathanWalker — APPROVED** [review]

**Comment by jarmani** [comment]
Any news on this one ? Thanks !

**Comment by NathanWalker** [comment]
Hi @INiiS and @jarmani, we began switching the transient permissions plugin usages throughout various plugins to:
https://github.com/nativescript-community/perms
and was reason we had delayed here. Let’s merge this and do a patch rather and we can switch the transient perms usage later. Thank you for this contribution.

**Comment by NathanWalker** [comment]
Published with 8.2.0

**Pull request merged**
