### PR TITLE
feat(geolocation): remove permissions from plugin

### LINKED ISSUE #164: [nativescript/geolocation] Android bundle upload checks ACCESS_BACKGROUND_LOCATION
I recently integrated this plugin into my app to check the current user location on user behalf (user actively presses a button for fetching the location). No `geolocation.watchLocation(...)` has been added, I just use ` geolocation.getCurrentLocation(...)`. When building my app and uploading the aab to the PlayStore it told me that the app permission changes for ACCESS_BACKGROUND_LOCATION.

I haven't added this permission in AndroidManifest.xml nor do I plan to use this feature. I just use ACCESS_COARSE_LOCATION and ACCESS_FINE_LOCATION for fetching current user location.

Could you please give me a tipp on how I can get rid of this message when uploading the bundle?

### LINKED ISSUE #192: [@nativescript/geolocation] android: Remove background location permission
Coming in April 2022 Google will require for developers to provide how do they use data and sensitive permissions: https://android-developers.googleblog.com/2021/10/launching-data-safety-in-play-console.html . Seems the background location permission is considered a sensitive one and you are **required** to provide written explanation and a video for what are you using this: https://support.google.com/googleplay/android-developer/answer/9799150?hl=en
Since the permission is automatically added by the geolocation plugin even if the app does not use background it will cause problems with apps in the Play Store. 

Can we do one of the following:
* Remove the `android.permission.ACCESS_BACKGROUND_LOCATION` from the manifest of the plugin and remove it from code that requests it. Add a section in the README that in case users that need this permission it should be manually added in the apps manifest file and requested from the app itself. 
* Provide somehow configuration options for users to remove the permission from their app in case it is not used. 
* Split background functions in a separate plugin

### PR DESCRIPTION
**Pull request by bradmartin**
- Document permissions on README with links to Android docs
- Remove manifest with permissions
- Bump plugin version

### CODE REVIEW

**Comment by bradmartin** [comment]
Related #192 & #164

**Comment by edusperoni** [comment]
LGTM. Just need to make sure to highlight this as a breaking change for 8.0

**Comment by bradmartin** [comment]
I'll add that note to the README and publish it out.

**Comment by bradmartin** [comment]
8.0.0 published.

**Pull request merged**
