### PR TITLE
feat(local-notifications): allow requesting send notifications permission on Android 13+ devices

### LINKED ISSUE #336: [@nativescript/local-notifications] [Android] Requires runtime permission dialog to allow notifications.
It appears that android13 (SDK33) now requires a runtime permission for setting local notifications:
https://developer.android.com/develop/ui/views/notifications/notification-permission#user-choice

I get this error when running the `LocalNotifications.schedule` method: **`Permission not granted.`**.

I've tried just adding this permission: `<uses-permission android:name="android.permission.POST_NOTIFICATIONS"/>` but nothing changes.

If I grant notification permissions to the app via `App info > Permissions` then everything works fine again.

### PR DESCRIPTION
**Pull request by agonper**
This PR updates the local-notifications plugin for hasPermission and requestPermission to work as expected on Android 13+ devices (asking for the corresponding permission). The behaviour is equivalent to that of iOS.

Fixes #336

### CODE REVIEW

**Comment by agonper** [comment]
Hello @NathanWalker, any chance this getting merged anytime soon? Thanks!

**Comment by NathanWalker** [comment]
@agonper thank you so much for this! Let’s switch to making transient on https://github.com/nativescript-community/perms as a better permissions handler. If able to switch up would be amazing but lemme know, otherwise we could merge and I could switch up in couple days to publish a minor bump.

**Comment by agonper** [comment]
Hello @NathanWalker, you are welcome! Thanks for the reply. I checked the solution you're suggesting for permissions handling, but I saw in the docs that asking for notification delivery permissions in Android is not yet supported by the community alternative. Am I wrong?

**Comment by NathanWalker** [comment]
Let's confirm with @farfromrefug and we can help add it there if needed.

**Comment by NathanWalker** [comment]
Looks like it's already there 👍  https://github.com/nativescript-community/perms/blob/master/src/perms/index.android.ts#L144

**Comment by agonper** [comment]
Oh, I did not check the code, just the README 😄

Done! Switched to the suggested solution.

If there's anything else, please let me know.

**Comment by NathanWalker** [comment]
Sweet! nice work @agonper 🤗

**Comment by NathanWalker** [comment]
6.1.0 published with the addition.

**Comment by agonper** [comment]
Great! Thanks for the compliment @NathanWalker!

I tried to install the new version in one of my projects, however, it seems that something happened during the release. The android aar file is missing in the npm package now:

image

Could you have a look please? Thanks!

**Comment by NathanWalker** [comment]
Hmm @agonper will look in moment and publish patch shortly.

**Comment by NathanWalker** [comment]
Should be resolved in 6.1.1 @agonper - lemme know if further issue. I added an extra check in the build.all step to ensure that doesn't happen again. Looked to be race condition on copy with the platforms folder on publish.
https://github.com/NativeScript/plugins/commit/25b2055537b181cd53cc74ed1c42485d8afce6d9

**Comment by agonper** [comment]
I can confirm it's solved! Thank you very much @NathanWalker for the quick check!!

**Comment by joaomsg11** [comment]
Tried to use this with the most recent version of local-notifications but it seems like it is not possible again (i also see that the changes to the readme made in this pr were reverted by the pr in https://github.com/NativeScript/plugins/pull/458/files) 
Is it not supported anymore?

**Pull request merged**
