### PR TITLE
feat(local-notifications): Improved interval scheduling

### LINKED ISSUE #73: [@nativescript/local-notifications] Custom interval not working on iOS - incomplete feature
Hi,
after updating plugin to version 5.1.0, which introduce the capacity of set a custom number interval (in days) when notification is scheduled, I noticed that custom intervals not works on iOS.
For example when I set a notification to schedule every X days (it works nice if scheduled daily).

In the iOS implementation of the plugin, call to method NSCalendar.**componentsFromDate** should be called with a **CalendarUnit** object and **date** object according to [apple reference](https://developer.apple.com/documentation/foundation/nscalendar/1414841-components?language=objc
) but CalendarUnit can only represent a specific range unit such minute, hour, day, month, etc. so currently is impossible to schedule a notification that triggers, for example, every 2 days and when this value is passed it introduces the insertion of a badly scheduled notification.

Example
```
LocalNotifications.schedule([
	{
		title: 'The title',
		body: 'Recurs every minute until cancelled',
                ...
		interval: 2,
		at: new Date(new Date().getTime() + 10 * 1000), // 10 seconds from now
	},
]).then(...)
```

Tested with
@nativescript/ios: "7.0.0"
@nativescript/core: "7.0.9"
nativescript-cli version 7.1.2

I hope this may help anyone, any suggestions are appreciated.
Thank you.

### PR DESCRIPTION
**Pull request by insytes**
Closes #73 

### What's new?

Allows notifications to be repeated with more precise intervals.

`ScheduleOptions.interval` can now be defined as either a `ScheduleInterval` or an object describing an interval
`{ [ScheduleInterval]: number }`

Example: 
`interval: 'day'` _*Existing functionality_
`interval: { 'second' 90 } // on iOS a minimum of 60 seconds is still required.`
`interval: { 'minute': 15 }`
`interval: { 'hour: 6 }`

A new boolean option is added `ScheduleOptions.displayImmediately`

This can only be used when an `interval` is provided.
It cannot be used when a trigger is defined as an exact date using `at`.

When `ScheduleOptions.displayImmediately` is true, a separate notification will be scheduled that will be displayed ASAP.

### Known limitations

The limitations on the new iOS Notification API (iOS 10+) means that notifications cannot be scheduled at an exact repeating interval after a precise date is defined.

In other words, we cannot define a notification like this:

```
// Can we trigger a notification at this exact time and repeat every 15 minutes? No.
LocalNotifications.schedule([{
  // ...
  at: new Date(new Date().getTime() + 10 * 1000), // 10 seconds from now
  interval: {
    'minute': 15
  },
}]);
```

The only option when using `at` is the existing behaviour of the plugin, a calendar unit.
```
// The only option is to provide a calendar unit for repeating this notification.
LocalNotifications.schedule([{
  // ...
  at: new Date(new Date().getTime() + 10 * 1000), // 10 seconds from now
  interval: 'hour'
  // display this notification at this time and repeat on the hour.
}]);
```

### Using the new stuff

With the newly available options we can schedule a notification to repeat on a calendar unit, multiplied by a given amount.

For example:
```
// Display notification & repeat every 15 minutes
LocalNotifications.schedule([{
  // ...
  interval: {
    'minute': 15
  },
  displayImmediately: true,
}]);
```

```
// Display notification in 90 minutes and repeat every 90 minutes
LocalNotifications.schedule([{
  // ...
  interval: {
    'minutes': 90
  },
}]);
```

Using the existing options as before:

```
// Display notification at specific date and repeat in 1 hour
LocalNotifications.schedule([{
  // ...
  interval: 'hour',
  at: new Date(new Date().getTime() + 10 * 1000), // 10 seconds from now
}]);
```

### Proceed?

Some more eyes on manual testing would be great.

Given the limitations on iOS I feel this change provides the best quick wins for slightly more control over repeating intervals.

Any thoughts?

### CODE REVIEW

**Comment by insytes** [comment]
@cla-bot check

**Comment by NathanWalker** [comment]
Excellent work @insytes 😍

**Comment by NathanWalker** [comment]
Adding the description notes into the README to document the new ability would be good. It can also make note of the iOS minimum on seconds, we can then publish this with a minor bump.

**Comment by insytes** [comment]
@NathanWalker README updated, I added the iOS note to the [ScheduleOptions](https://github.com/insytes/plugins/tree/73-interval-scheduling/packages/local-notifications#scheduleoptions) table.

**Review by NathanWalker — APPROVED** [review]

**Comment by NathanWalker** [comment]
Released with 6.2.0

**Pull request merged**
